### PR TITLE
2020-07-23 DB: added scripts for gcc 8 and 9, openssl 1.1.1, curl 7.71.1, dpkg and mongodb (including 4.2.8)

### PR DESCRIPTION
**Pull request by dbierer**
For all `lfphp-get` scripts:
* If you don't supply the `VERSION` you'll get prompted
* You need to supply a version number if using the `--compile` flag

# gcc
Usage: lfphp-get gcc [VERSION] [--compile]
Example: `lfphp-get gcc 9.3.0 --compile`
NOTES: 
* Takes 2 to 3 hours to compile if using the `--compile` option
* Binaries are currently located on unlikelysource.com:
```
http://opensource.unlikelysource.com/gcc-9.3.0.zip
http://opensource.unlikelysource.com/gcc-8.4.0.zip
```
# dpkg
Usage: Usage: lfphp-get dpkg [VERSION] [--compile]
Example: `lfphp-get dpkg 1.19.7 --compile`
NOTES:
The only version supported is 1.19.7 Seems to work OK.  Used it to install MongoDB 4.2.8.  Because the OS libraries are not previously recognized by `dpkg` when you compile you see lots of errors.  Accordingly, you'll need to use the `--force-depends` and `--no-triggers` flags.  In order to use `dpkg` proceed as in the following example which installed MongoDB server 4.2.8:
```
wget http://repo.mongodb.org/apt/debian/dists/buster/mongodb-org/4.2/main/binary-amd64/mongodb-org-server_4.2.8_amd64.deb
dpkg -i --force-depends --no-triggers mongodb-org-server_4.2.8_amd64.deb
```
# openssl
Usage: lfphp-get openssl [VERSION] [--compile]
Example: `Usage: lfphp-get openssl 1.1.1 --compile`
NOTES:
The only version supported is 1.1.1.  Replaces the current version of `openssl` (1.0.68).  Includes the *.h files.

# curl
Usage: lfphp-get curl [VERSION] [--compile]
Example: `Usage: lfphp-get curl 7.71.1 --compile`
NOTES:
The only version supported is 7.71.1.  Replaces the current version of `curl`.  If you don't pre-install OpenSSL 1.1.x you'll get a warning that `curl` and `libcurl` don't match.  Includes the *.h files.

# mongodb
Usage: lfphp-get mongodb [VERSION] [--compile]
Example: `lfphp-get mongodb 4.2.8 --compile`
NOTES:
If you install 4.2.8, all hell breaks loose.  If you use the `--compile` option you'll also need to install `dpkg`.  To run MongoDB 4.2.8 you'll also need to upgrade OpenSSL to version 1.1.1.  This can be done as follows:
```
lfphp-get openssl 1.1.1
```
Seems to work OK.  Tested using examples from the "Learn MongoDB 4.x" book from Packt (uh ... what was that author's name again???)

### CODE REVIEW

**Comment by dbierer** [comment]
## tree
Added `tree_LfPHP_setup.sh.txt` script for the linux "tree" command.
Usage: `lfphp-get tree [--compile]`

**Comment by andrewscaya** [comment]
@dbierer Many thanks, Doug!

These will be very helpful to the LfPHP community, I'm sure! 👍 

I'll only be making a few adjustments to make everything backward-compatible.

Cheers!

**Comment by andrewscaya** [comment]
@dbierer Fixes have been added in ec5b34b4b2b52c209d1822ae084121ad37cadb2b.

**Comment by andrewscaya** [comment]
@dbierer Eventually, we'll have to find a comprehensive strategy for all the symlinks to the MAN entries in the OpenSSL installation script...

**Comment by andrewscaya** [comment]
@dbierer I'll be compiling the binaries for these packages within the next three weeks. You can therefore expect them to be GA in early September! 💯

**Comment by andrewscaya** [comment]
I'll be shutting down this thread once they are available to the LfPHP users in September.

/cc @andrewscaya

**Comment by dbierer** [comment]
Andrew --
  
  
   
  
  
   100% agree.  Otherwise too many dangling threads. Sigh ...
  
  
   
  
  
   --db
  
  
   On August 19, 2020 at 4:59 PM Andrew Caya <notifications@github.com> wrote: 
   
   
   
   @dbierer Eventually, we'll have to find a comprehensive strategy for all the symlinks to the MAN entries in the OpenSSL installation script...

**Comment by dbierer** [comment]
excellent!
  
  
   On August 19, 2020 at 5:01 PM Andrew Caya <notifications@github.com> wrote: 
   
   
   
   @dbierer I'll be compiling the binaries for these packages within the next three weeks. You can therefore expect them to be GA in early September! 💯

**Pull request merged**
